### PR TITLE
Remove VLA to support MSVC

### LINKED ISSUE #2: Windows C Code errors
Currently experiencing a bug on version 1.0.6 when building on windows.

I have tried a flutter clean, and cache repair still no luck.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22000.2176], locale en-ZA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.1)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.80.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```
Nuget.exe not found, trying to download or use cached version.
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(36,16): error C2057: expected constant expression [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(36,27): error C2466: cannot allocate an array of constant size 0 [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(36,29): error C2057: expected constant expression [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(36,40): error C2466: cannot allocate an array of constant size 0 [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(36,40): error C2087: 'factors': missing subscript [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(36,8): error C2133: 'factors': unknown size [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(37,36): warning C4034: sizeof returns 0 [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(208,15): error C2057: expected constant expression [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(208,26): error C2466: cannot allocate an array of constant size 0 [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(208,8): error C2133: 'colors': unknown size [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
E:\pageme\windows\flutter\ephemeral\.plugin_symlinks\blurhash_ffi\src\blurhash_ffi.c(282,14): warning C4090: 'function': different 'const' qualifiers [E:\pageme\build\windows\plugins\blurhash_ffi\shared\blurhash_ffi.vcxproj]
Exception: Build process failed.

```

### PR DESCRIPTION
**Pull request by wh201906**
This fixes #2
It looks like you are planning to migrate the native code to rust to resolve #2, but I think a MSVC compatible release before the migration is also needed.

### CODE REVIEW

**Comment by dhikshith12** [comment]
I Appreciate your work and Thanks for this PR, I Tried Something Similar by replacing VLA with dynamic memory allocation, but somehow it was causing runtime errors, have you verified if your branch `wh201906:fix_windows_vla` is working on a windows device on your side.

Thank you.

**Comment by wh201906** [comment]
I guess it's caused by the size_t type. For Windows x64 the size_t is an unsigned 64bit number, but the int type in Dart is signed 64bit number.

**Review by dhikshith12 — DISMISSED** [review]

**Comment by dhikshith12** [comment]
I'll try the example app to run on windows 🤞

**Comment by wh201906** [comment]
I just tested them and I also got the blank image view when decoding.
However, it looks like the decoding result from the native C code is good. I added some code to print the decoding result and tested them on both Windows and Linux, then I got the same result.
<details>
<summary>Patch to show the head and the and of the decoding result</summary>

```
diff --git a/lib/blurhash.dart b/lib/blurhash.dart
index 63d8de9..29f719b 100644
--- a/lib/blurhash.dart
+++ b/lib/blurhash.dart
@@ -341,6 +341,38 @@ class BlurhashFFI {
     return completer.future;
   }
 
+  void printUint8ListInHex(Uint8List list) {
+    print("data length: " + list.length.toString());
+    print("head:");
+    int printLength = list.length > 256 ? 256 : list.length;
+    String hexString = "";
+    int i = 0;
+    for (i = 0; i < printLength; i++) {
+      hexString += list[i].toRadixString(16).padLeft(2, '0');
+      if (i % 16 == 15) {
+        print(hexString);
+        hexString = "";
+      }
+    }
+    if (i % 16 == 15) {
+      print(hexString);
+    }
+
+    print("end:");
+    int startLength = list.length > 256 ? list.length - 256 : 0;
+    Uint8List lastBytes = list.sublist(startLength);
+    for (i = 0; i < printLength; i++) {
+      hexString += lastBytes[i].toRadixString(16).padLeft(2, '0');
+      if (i % 16 == 15) {
+        print(hexString);
+        hexString = "";
+      }
+    }
+    if (i % 16 == 15) {
+      print(hexString);
+    }
+  }
+
   void isolateEntryPoint(SendPort sendPort) async {
     void onSend(dynamic data) {
       try {
@@ -366,6 +398,7 @@ class BlurhashFFI {
           data.free();
           final Uint8List resultImage =
               result.asTypedList(data.width * data.height * data.channels);
+          printUint8ListInHex(resultImage);
           _bindings.freePixelArray(result);
           final _DecodeResponse response =
               _DecodeResponse(data.id, resultImage);

```

</details>

<details>
<summary>Result on linux</summary>

```
linux
flutter: data length: 57600
flutter: head:
flutter: 004346ff004346ff004346ff004346ff
flutter: 004346ff004346ff004346ff004346ff
flutter: 004246ff004246ff004245ff004245ff
flutter: 004245ff004245ff004144ff004144ff
flutter: 004144ff004043ff034043ff0e4042ff
flutter: 163f42ff1c3f42ff223f41ff263e41ff
flutter: 2b3e40ff2f3d3fff333d3fff363c3eff
flutter: 393c3eff3d3b3dff403b3cff433a3bff
flutter: 463a3bff48393aff4b3939ff4e3838ff
flutter: 503737ff523736ff553635ff573534ff
flutter: 593534ff5b3433ff5d3331ff5f3330ff
flutter: 61322fff63312eff64312dff66302cff
flutter: 682f2bff692f2aff6a2e29ff6c2d28ff
flutter: 6d2d26ff6e2c25ff6f2c24ff712b23ff
flutter: 722b22ff722a21ff732a20ff74291fff
flutter: 75291eff75281dff76281cff77281bff
flutter: end:
flutter: b64536ffb64536ffb74536ffb74636ff
flutter: b84636ffb84637ffb84737ffb84737ff
flutter: b84737ffb84737ffb84838ffb74838ff
flutter: b74838ffb64838ffb64839ffb54839ff
flutter: b44939ffb34939ffb24939ffb1493aff
flutter: af493affae493affac493affab493bff
flutter: a9493bffa7493bffa5493bffa3493cff
flutter: a1493cff9f493cff9c493cff9a493cff
flutter: 97493dff95493dff92493dff8f493dff
flutter: 8c493eff89493eff86493eff83483eff
flutter: 7f483eff7c483eff78483fff75483fff
flutter: 71483fff6e483fff6a473fff66473fff
flutter: 624740ff5f4740ff5b4740ff574740ff
flutter: 534740ff504740ff4c4640ff494640ff
flutter: 454640ff424640ff3f4640ff3d4640ff
flutter: 3b4641ff394641ff384641ff374641ff
flutter: data length: 57600
flutter: head:
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff060000ff120000ff
flutter: 1a0000ff210000ff270000ff2c0c0cff
flutter: 311818ff352121ff3a2828ff3e2e2eff
flutter: 413333ff453838ff493c3cff4c4040ff
flutter: 4f4444ff524848ff554b4bff584f4fff
flutter: 5b5252ff5d5555ff605757ff625a5aff
flutter: 655c5cff675f5fff696161ff6b6363ff
flutter: 6d6565ff6f6767ff716868ff736a6aff
flutter: 746c6cff766d6dff776e6eff786f6fff
flutter: 7a7070ff7b7171ff7c7272ff7d7373ff
flutter: 7e7474ff7f7474ff7f7575ff807575ff
flutter: 807575ff817575ff817575ff817575ff
flutter: 817575ff827575ff817575ff817474ff
flutter: end:
flutter: 4c4a4aff4a4949ff494848ff474747ff
flutter: 454545ff434444ff414242ff3e4040ff
flutter: 3b3e3eff383c3cff353939ff313636ff
flutter: 2c3434ff273030ff222d2dff1b2929ff
flutter: 122525ff042020ff001a1aff001313ff
flutter: 000808ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: data length: 57600
flutter: head:
flutter: 3d4d43ff3d4d43ff3e4d44ff3f4d44ff
flutter: 404d44ff414e45ff434f45ff454f46ff
flutter: 475047ff4a5147ff4c5248ff4f5349ff
flutter: 52544aff54554bff57564cff5a574dff
flutter: 5d584eff605a4fff635b50ff655c51ff
flutter: 685d52ff6b5e53ff6d5f54ff706055ff
flutter: 736156ff756257ff776357ff7a6458ff
flutter: 7c6559ff7e6659ff80675aff82675aff
flutter: 84685aff85685aff87695bff88695bff
flutter: 8a6a5bff8b6a5bff8c6a5aff8d6a5aff
flutter: 8e6a5aff8f6a59ff906a59ff906a58ff
flutter: 916a58ff916957ff926956ff926955ff
flutter: 926855ff926854ff926753ff926652ff
flutter: 926651ff926550ff91644fff91634eff
flutter: 90634dff90624bff8f614bff8f604aff
flutter: 8e6049ff8d5f48ff8c5e47ff8c5e47ff
flutter: end:
flutter: b18a73ffb38d74ffb59076ffb79278ff
flutter: b9957affbb987cffbd9b7effbf9e80ff
flutter: c1a182ffc3a484ffc5a686ffc7a988ff
flutter: c9ac8affcbae8cffccb18effceb390ff
flutter: d0b592ffd2b893ffd3ba95ffd5bc97ff
flutter: d6be98ffd7c09affd9c19bffdac39cff
flutter: dbc49effdcc69fffddc7a0ffdec8a1ff
flutter: dec9a2ffdfcaa3ffdfcba3ffe0cca4ff
flutter: e0cca5ffe1cda5ffe1cda6ffe1cda6ff
flutter: e1cea7ffe1cea7ffe1cea7ffe1cea7ff
flutter: e1cea7ffe1cea7ffe1cda8ffe0cda8ff
flutter: e0cda7ffe0cda7ffdfcca7ffdfcca7ff
flutter: dfcba7ffdecba7ffdecaa7ffddcaa6ff
flutter: ddcaa6ffddc9a6ffdcc9a6ffdcc8a6ff
flutter: dcc8a6ffdbc8a5ffdbc7a5ffdbc7a5ff
flutter: dbc7a5ffdbc7a5ffdac7a5ffdac7a5ff
```

</details>

<details>
<summary>Result on Windows</summary>

```
windows
flutter: data length: 57600
flutter: head:
flutter: 004346ff004346ff004346ff004346ff
flutter: 004346ff004346ff004346ff004346ff
flutter: 004246ff004246ff004245ff004245ff
flutter: 004245ff004245ff004144ff004144ff
flutter: 004144ff004043ff034043ff0e4042ff
flutter: 163f42ff1c3f42ff223f41ff263e41ff
flutter: 2b3e40ff2f3d3fff333d3fff363c3eff
flutter: 393c3eff3d3b3dff403b3cff433a3bff
flutter: 463a3bff48393aff4b3939ff4e3838ff
flutter: 503737ff523736ff553635ff573534ff
flutter: 593534ff5b3433ff5d3331ff5f3330ff
flutter: 61322fff63312eff64312dff66302cff
flutter: 682f2bff692f2aff6a2e29ff6c2d28ff
flutter: 6d2d26ff6e2c25ff6f2c24ff712b23ff
flutter: 722b22ff722a21ff732a20ff74291fff
flutter: 75291eff75281dff76281cff77281bff
flutter: end:
flutter: b64536ffb64536ffb74536ffb74636ff
flutter: b84636ffb84637ffb84737ffb84737ff
flutter: b84737ffb84737ffb84838ffb74838ff
flutter: b74838ffb64838ffb64839ffb54839ff
flutter: b44939ffb34939ffb24939ffb1493aff
flutter: af493affae493affac493affab493bff
flutter: a9493bffa7493bffa5493bffa3493cff
flutter: a1493cff9f493cff9c493cff9a493cff
flutter: 97493dff95493dff92493dff8f493dff
flutter: 8c493eff89493eff86493eff83483eff
flutter: 7f483eff7c483eff78483fff75483fff
flutter: 71483fff6e483fff6a473fff66473fff
flutter: 624740ff5f4740ff5b4740ff574740ff
flutter: 534740ff504740ff4c4640ff494640ff
flutter: 454640ff424640ff3f4640ff3d4640ff
flutter: 3b4641ff394641ff384641ff374641ff
flutter: data length: 57600
flutter: head:
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff060000ff120000ff
flutter: 1a0000ff210000ff270000ff2c0c0cff
flutter: 311818ff352121ff3a2828ff3e2e2eff
flutter: 413333ff453838ff493c3cff4c4040ff
flutter: 4f4444ff524848ff554b4bff584f4fff
flutter: 5b5252ff5d5555ff605757ff625a5aff
flutter: 655c5cff675f5fff696161ff6b6363ff
flutter: 6d6565ff6f6767ff716868ff736a6aff
flutter: 746c6cff766d6dff776e6eff786f6fff
flutter: 7a7070ff7b7171ff7c7272ff7d7373ff
flutter: 7e7474ff7f7474ff7f7575ff807575ff
flutter: 807575ff817575ff817575ff817575ff
flutter: 817575ff827575ff817575ff817474ff
flutter: end:
flutter: 4c4a4aff4a4949ff494848ff474747ff
flutter: 454545ff434444ff414242ff3e4040ff
flutter: 3b3e3eff383c3cff353939ff313636ff
flutter: 2c3434ff273030ff222d2dff1b2929ff
flutter: 122525ff042020ff001a1aff001313ff
flutter: 000808ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: 000000ff000000ff000000ff000000ff
flutter: data length: 57600
flutter: head:
flutter: 3d4d43ff3d4d43ff3e4d44ff3f4d44ff
flutter: 404d44ff414e45ff434f45ff454f46ff
flutter: 475047ff4a5147ff4c5248ff4f5349ff
flutter: 52544aff54554bff57564cff5a574dff
flutter: 5d584eff605a4fff635b50ff655c51ff
flutter: 685d52ff6b5e53ff6d5f54ff706055ff
flutter: 736156ff756257ff776357ff7a6458ff
flutter: 7c6559ff7e6659ff80675aff82675aff
flutter: 84685aff85685aff87695bff88695bff
flutter: 8a6a5bff8b6a5bff8c6a5aff8d6a5aff
flutter: 8e6a5aff8f6a59ff906a59ff906a58ff
flutter: 916a58ff916957ff926956ff926955ff
flutter: 926855ff926854ff926753ff926652ff
flutter: 926651ff926550ff91644fff91634eff
flutter: 90634dff90624bff8f614bff8f604aff
flutter: 8e6049ff8d5f48ff8c5e47ff8c5e47ff
flutter: end:
flutter: b18a73ffb38d74ffb59076ffb79278ff
flutter: b9957affbb987cffbd9b7effbf9e80ff
flutter: c1a182ffc3a484ffc5a686ffc7a988ff
flutter: c9ac8affcbae8cffccb18effceb390ff
flutter: d0b592ffd2b893ffd3ba95ffd5bc97ff
flutter: d6be98ffd7c09affd9c19bffdac39cff
flutter: dbc49effdcc69fffddc7a0ffdec8a1ff
flutter: dec9a2ffdfcaa3ffdfcba3ffe0cca4ff
flutter: e0cca5ffe1cda5ffe1cda6ffe1cda6ff
flutter: e1cea7ffe1cea7ffe1cea7ffe1cea7ff
flutter: e1cea7ffe1cea7ffe1cda8ffe0cda8ff
flutter: e0cda7ffe0cda7ffdfcca7ffdfcca7ff
flutter: dfcba7ffdecba7ffdecaa7ffddcaa6ff
flutter: ddcaa6ffddc9a6ffdcc9a6ffdcc8a6ff
flutter: dcc8a6ffdbc8a5ffdbc7a5ffdbc7a5ff
flutter: dbc7a5ffdbc7a5ffdac7a5ffdac7a5ff
```

</details>

So I guess it's something wrong in the Dart side.

**Comment by dhikshith12** [comment]
That proves native part is working fine on windows, like it does in linux and mac, I've tried different methods of rendering the `ui:Image` output, but they are all giving the same white image.

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

class UIImage extends StatelessWidget {
  final ui.Image image;

  const UIImage({
    Key key,
    @required this.image,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CustomPaint(painter: _UIImagePainter(image));
  }
}

class _UIImagePainter extends CustomPainter {
  final ui.Image image;

  _UIImagePainter(this.image);

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawImageRect(
      image,
      Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()),
      Rect.fromLTWH(0, 0, size.width, size.height),
      Paint(),
    );
  }

  @override
  bool shouldRepaint(_UIImagePainter oldDelegate) {
    return image != oldDelegate.image;
  }
}
``` 

```dart
RawImage(
    image: snap.data
)
```
in place of this
https://github.com/folksable/blurhash_ffi/blob/e51e43f2a287d9cb288508883bd63c90e16fa59a/lib/blurhashffi_widget.dart#L174-L180

So it's not the problem with rendering output either, so this has to be an issue with how ui:Image is constructed from the data that's coming from the native side.

**Comment by wh201906** [comment]
Maybe there is something wrong in the `_createBmp()`
https://github.com/folksable/blurhash_ffi/blob/e51e43f2a287d9cb288508883bd63c90e16fa59a/lib/blurhash.dart#L541-L565

You can check the BMP data in the `bmp.buffer` and see if it’s consistent across all platforms

**Comment by dhikshith12** [comment]
`_createBmp()` is only being used on the web, on other platforms it's using `ui.decodeImageFromPixels` 

https://github.com/folksable/blurhash_ffi/blob/e51e43f2a287d9cb288508883bd63c90e16fa59a/lib/blurhash.dart#L216-L219
I tried different PixelFormat enum, but that's not fixing the problem.

https://github.com/folksable/blurhash_ffi/blob/e51e43f2a287d9cb288508883bd63c90e16fa59a/lib/blurhash.dart#L219-L222

**Comment by wh201906** [comment]
Could you please check the errors (if any) from `decodeImageFromPixels()` and all arguments of it? Are the arguments the same across all platforms?

**Comment by wh201906** [comment]
By the way, this PR is a fix for the native C code. I think it's safe to merge it because we've proved that the compilation on Windows works and the data from the native C code is the same as the one in other platforms.
As for the bug in the decoding process, we can discuss it after this PR is merged or create a new issue for it.

**Comment by wh201906** [comment]
Thanks.

**Pull request merged**
